import type { Product } from "@/types/product";

// CMS용 더미 상품 데이터
export const dummyAdminProducts: Product[] = [
  {
    id: 1,
    name: "프리미엄 닭가슴살",
    price: 15000,
    category: "단백질",
    imageUrl: "https://via.placeholder.com/300x300?text=Chicken+Breast",
    brand: "Energy Factory",
    weight: 1000,
    weightUnit: "g",
    stock: 50,
    status: "AVAILABLE",
    averageRating: 4.5,
    reviewCount: 120,
    tags: ["고단백", "저지방", "다이어트"],
    originalPrice: 18000,
    discount: 17,
  },
  {
    id: 2,
    name: "오트밀 1kg",
    price: 12000,
    category: "탄수화물",
    imageUrl: "https://via.placeholder.com/300x300?text=Oatmeal",
    brand: "Energy Factory",
    weight: 1000,
    weightUnit: "g",
    stock: 100,
    status: "AVAILABLE",
    averageRating: 4.8,
    reviewCount: 250,
    tags: ["통곡물", "식이섬유", "아침식사"],
  },
  {
    id: 3,
    name: "프로틴 파우더 초콜릿",
    price: 45000,
    category: "보충제",
    imageUrl: "https://via.placeholder.com/300x300?text=Protein+Powder",
    brand: "Energy Factory",
    weight: 2000,
    weightUnit: "g",
    stock: 30,
    status: "AVAILABLE",
    averageRating: 4.3,
    reviewCount: 180,
    tags: ["WPI", "고단백", "근육증가"],
    originalPrice: 50000,
    discount: 10,
  },
  {
    id: 4,
    name: "아몬드 500g",
    price: 18000,
    category: "견과류",
    imageUrl: "https://via.placeholder.com/300x300?text=Almonds",
    brand: "Energy Factory",
    weight: 500,
    weightUnit: "g",
    stock: 75,
    status: "AVAILABLE",
    averageRating: 4.6,
    reviewCount: 95,
    tags: ["건강간식", "불포화지방", "비타민E"],
  },
  {
    id: 5,
    name: "현미 5kg",
    price: 25000,
    category: "탄수화물",
    imageUrl: "https://via.placeholder.com/300x300?text=Brown+Rice",
    brand: "Energy Factory",
    weight: 5000,
    weightUnit: "g",
    stock: 20,
    status: "LOW_STOCK",
    averageRating: 4.7,
    reviewCount: 310,
    tags: ["통곡물", "현미", "건강밥"],
  },
  {
    id: 6,
    name: "연어 필렛 (냉동)",
    price: 32000,
    category: "단백질",
    imageUrl: "https://via.placeholder.com/300x300?text=Salmon+Fillet",
    brand: "Energy Factory",
    weight: 800,
    weightUnit: "g",
    stock: 0,
    status: "OUT_OF_STOCK",
    averageRating: 4.9,
    reviewCount: 87,
    tags: ["오메가3", "고단백", "냉동"],
  },
  {
    id: 7,
    name: "그릭 요거트 플레인",
    price: 8500,
    category: "유제품",
    imageUrl: "https://via.placeholder.com/300x300?text=Greek+Yogurt",
    brand: "Energy Factory",
    weight: 500,
    weightUnit: "g",
    stock: 150,
    status: "AVAILABLE",
    averageRating: 4.4,
    reviewCount: 210,
    tags: ["고단백", "프로바이오틱스", "저지방"],
  },
  {
    id: 8,
    name: "브로콜리 (냉동)",
    price: 6500,
    category: "채소",
    imageUrl: "https://via.placeholder.com/300x300?text=Broccoli",
    brand: "Energy Factory",
    weight: 1000,
    weightUnit: "g",
    stock: 200,
    status: "AVAILABLE",
    averageRating: 4.2,
    reviewCount: 65,
    tags: ["저칼로리", "비타민C", "식이섬유"],
  },
  {
    id: 9,
    name: "BCAA 파우더",
    price: 38000,
    category: "보충제",
    imageUrl: "https://via.placeholder.com/300x300?text=BCAA",
    brand: "Energy Factory",
    weight: 500,
    weightUnit: "g",
    stock: 45,
    status: "AVAILABLE",
    averageRating: 4.1,
    reviewCount: 92,
    tags: ["운동보조", "근육회복", "아미노산"],
    originalPrice: 42000,
    discount: 10,
  },
  {
    id: 10,
    name: "고구마 3kg",
    price: 15000,
    category: "탄수화물",
    imageUrl: "https://via.placeholder.com/300x300?text=Sweet+Potato",
    brand: "Energy Factory",
    weight: 3000,
    weightUnit: "g",
    stock: 60,
    status: "AVAILABLE",
    averageRating: 4.8,
    reviewCount: 340,
    tags: ["복합탄수화물", "식이섬유", "비타민A"],
  },
];

// 상품 상태 옵션
export const productStatusOptions = [
  { value: "AVAILABLE", label: "판매중", color: "text-green-600 bg-green-50" },
  { value: "LOW_STOCK", label: "재고부족", color: "text-yellow-600 bg-yellow-50" },
  { value: "OUT_OF_STOCK", label: "품절", color: "text-red-600 bg-red-50" },
  { value: "DISCONTINUED", label: "단종", color: "text-gray-600 bg-gray-50" },
] as const;

// 카테고리 옵션
export const categoryOptions = [
  "단백질",
  "탄수화물",
  "보충제",
  "견과류",
  "유제품",
  "채소",
  "기타",
] as const;
